FROM almalinux:9.3 AS build_image
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
ARG CORSIKA=corsika-77500

RUN yum update -y && yum install -y \
    csh \
    perl \
    gcc-fortran && \
    yum clean all

ADD $CORSIKA.tar.gz .
# CORSIKA compile options derived with coconut
COPY ./docker/corsika-config.h $CORSIKA/include/config.h

# build corsika
WORKDIR $CORSIKA
RUN ./coconut < /dev/null

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/

FROM almalinux:9.3-minimal
LABEL maintainer.name="VERITAS Collaboration"
LABEL maintainer.email="gernot.maier@desy.de"
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
ARG CORSIKA=corsika-77500
COPY --from=build_image /workdir/$CORSIKA/run /workdir/corsika-run

RUN microdnf update -y && microdnf install -y \
    gcc-fortran && \
    microdnf clean all

COPY ./config/ATMOSPHERE/atmprof*.dat /workdir/corsika-run/
# qgsjet tables (otherwise CORSIKA generates these tables during startup)
ADD https://syncandshare.desy.de/index.php/s/X9a4c5bYzy5p6nF/download /workdir/corsika-run/tables.dat

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/
